import Head from 'next/head';

export default function Formation() {
  return (
    <div>
      <Head>
        <title>Formation - Seneve Network</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>This is Formation Page</h1>
    </div>
  );
}
