import Head from 'next/head';

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Contact - Seneve Network</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>This is Contact Page</h1>
    </div>
  );
}
