import Head from 'next/head';

export default function Galerie() {
  return (
    <div>
      <Head>
        <title>Galerie - Seneve Network</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>This is Galerie Page</h1>
    </div>
  );
}
