import Head from 'next/head';

export default function Service() {
  return (
    <div>
      <Head>
        <title>Service - Seneve Network</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>This is Service Page</h1>
    </div>
  );
}
