import Head from 'next/head';

export default function Apropos() {
  return (
    <div>
      <Head>
        <title>Apropos - Seneve Network</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>This is Apropos Page</h1>
    </div>
  );
}
