import Head from 'next/head';

export default function Blog() {
  return (
    <div>
      <Head>
        <title>Blog - Seneve Network</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>This is Blog Page</h1>
    </div>
  );
}
